/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/core/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ArticleCard: typeof import('./components/article/ArticleCard.vue')['default']
    ArticleForm: typeof import('./components/article/ArticleForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuUser: typeof import('./components/profile/MenuUser.vue')['default']
    ModalConfirmation: typeof import('./components/core/ModalConfirmation.vue')['default']
    NavBar: typeof import('./components/core/NavBar.vue')['default']
    NotFound: typeof import('./components/core/NotFound.vue')['default']
    ProfilCard: typeof import('./components/profile/ProfilCard.vue')['default']
    ProfilForm: typeof import('./components/profile/ProfilForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeArea: typeof import('./components/core/SafeArea.vue')['default']
    StepConfirmation: typeof import('./components/auth/register/StepConfirmation.vue')['default']
    StepForgotPassword: typeof import('./components/auth/forgot/StepForgotPassword.vue')['default']
    StepSendEmail: typeof import('./components/auth/forgot/StepSendEmail.vue')['default']
    StepSetPassword: typeof import('./components/auth/register/StepSetPassword.vue')['default']
    StepUserInfo: typeof import('./components/auth/register/StepUserInfo.vue')['default']
    VListProfile: typeof import('./components/profile/VListProfile.vue')['default']
  }
}
